name: ${project.name}
version: ${project.version}
main: ${project.groupId}.${project.artifactId}.ParticleGuidesPlugin
author: FreshLlamanade
api-version: 1.19
softdepend:
  - Essentials

permissions:
  particleguides.guide.coords:
    description: Allows a player access to the /guide coords command
    default: true
  particleguides.guide.death:
    description: Allows a player access to the /guide death command
    default: true
  particleguides.guide.here:
    description: Allows a player access to the /guide here command
    default: true
  particleguides.guide.home:
    description: Allows a player access to the /guide home command
    default: true
  particleguides.guide.player:
    description: Allows a player access to the /guide player command
    default: true
  particleguides.guide.player.no-ask:
    description: Allows a player to create a guide to another player without asking
    default: op
    children:
      particleguides.guide.player: true
  particleguides.guide:
    description: Allows a player full access to the /guide command
    default: true
    children:
      particleguides.guide.coords: true
      particleguides.guide.death: true
      particleguides.guide.here: true
      particleguides.guide.home: true
      particleguides.guide.player: true
  particleguides.guide.limit.*:
    description: Adjust the maximum number of guides a player can create
    default: op
  particleguides.breadcrumbs:
    description: Allows a player access to the /breadcrumbs command
    default: true
  particleguides.breadcrumbs.limit.*:
    description: Adjust the maximum length of a player's breadcrumb trail
    default: op
  particleguides.admin:
    description: Allows a player to manage the plugin
    default: op
  particleguides.*:
    description: Allows a player full access to the plugin
    default: op
    children:
      particleguides.guide: true
      particleguides.guide.limit.*: true
      particleguides.breadcrumbs.limit.*: true
      particleguides.admin: true
